name: Reshaper Code Analysis

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
      
      - name: Adding Main Project Packages
        run: dotnet add AlertToCare/AlertToCare/AlertToCare.csproj package Npgsql.EntityFrameworkCore.PostgreSQL --version 3.1.4
          
      - name: Adding Test Project Packages
        run: dotnet add AlertToCare/AlertToCare.UnitTest/AlertToCare.UnitTest.csproj package xunit --version 2.4.0
        
      - name: Run resharper inspection
        run: jb inspectcode AlertToCare/AlertToCare.sln /output=insreport.xml

      - name: Run resharper duplicate code check
        run: jb dupfinder AlertToCare/AlertToCare.sln /output=dupreport.xml

      - name: Check Reports
        run: powershell ./resharper.ps1
